#!/bin/bash
#
# Phoenix Scanner Client - Setup Script
# Quickly set up the client for first use
#

set -e

echo "=================================================="
echo "Phoenix Scanner Client - Setup"
echo "=================================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check Python version
echo -e "${CYAN}Checking Python version...${NC}"
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 is not installed${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
echo -e "${GREEN}✓${NC} Found Python $PYTHON_VERSION"

# Check if version is 3.8+
REQUIRED_VERSION="3.8"
if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo -e "${RED}Error: Python 3.8+ is required${NC}"
    exit 1
fi

# Install dependencies
echo ""
echo -e "${CYAN}Installing dependencies...${NC}"
pip3 install --user -r requirements.txt
echo -e "${GREEN}✓${NC} Dependencies installed"

# Copy scanner list if not exists
if [ ! -f "scanner_list_actual.txt" ]; then
    if [ -f "../scanner_list_actual.txt" ]; then
        echo ""
        echo -e "${CYAN}Copying scanner list...${NC}"
        cp ../scanner_list_actual.txt .
        echo -e "${GREEN}✓${NC} Scanner list copied"
    fi
fi

# Create config if not exists
if [ ! -f "config.yaml" ]; then
    echo ""
    echo -e "${CYAN}Creating configuration file...${NC}"
    
    read -p "Phoenix Scanner API URL [http://localhost:8000]: " API_URL
    API_URL=${API_URL:-http://localhost:8000}
    
    read -p "Phoenix Scanner API Key: " API_KEY
    
    read -p "Phoenix Client ID (optional): " PHOENIX_CLIENT_ID
    read -p "Phoenix Client Secret (optional): " PHOENIX_CLIENT_SECRET
    read -p "Phoenix API URL (optional): " PHOENIX_API_URL
    
    cat > config.yaml << EOF
# Phoenix Scanner Client Configuration
# Generated by setup.sh on $(date)

# Required
api_url: $API_URL
api_key: $API_KEY

# Optional - Phoenix Platform Credentials
EOF
    
    if [ -n "$PHOENIX_CLIENT_ID" ]; then
        echo "phoenix_client_id: $PHOENIX_CLIENT_ID" >> config.yaml
    else
        echo "# phoenix_client_id: your-client-id" >> config.yaml
    fi
    
    if [ -n "$PHOENIX_CLIENT_SECRET" ]; then
        echo "phoenix_client_secret: $PHOENIX_CLIENT_SECRET" >> config.yaml
    else
        echo "# phoenix_client_secret: your-client-secret" >> config.yaml
    fi
    
    if [ -n "$PHOENIX_API_URL" ]; then
        echo "phoenix_api_url: $PHOENIX_API_URL" >> config.yaml
    else
        echo "# phoenix_api_url: https://api.demo.appsecphx.io" >> config.yaml
    fi
    
    cat >> config.yaml << EOF

# Defaults
default_scanner_type: auto
default_import_type: new
enable_batching: true
fix_data: true
timeout: 3600
verify_ssl: true
verbose: false
EOF
    
    echo -e "${GREEN}✓${NC} Configuration created: config.yaml"
else
    echo ""
    echo -e "${YELLOW}⚠${NC} config.yaml already exists, skipping configuration"
fi

# Test connection
echo ""
echo -e "${CYAN}Testing connection...${NC}"
if python3 -c "from phoenix_client import PhoenixScannerClient; import yaml; config = yaml.safe_load(open('config.yaml')); client = PhoenixScannerClient(config['api_url'], config['api_key']); result = client.health_check(); exit(0 if result.get('status') == 'healthy' else 1)" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Connection successful!"
else
    echo -e "${YELLOW}⚠${NC} Could not connect to API (this is OK if the service isn't running yet)"
    echo -e "  Start the service with: ${CYAN}cd ../phoenix-scanner-service && docker-compose up -d${NC}"
fi

# Summary
echo ""
echo "=================================================="
echo -e "${GREEN}Setup Complete!${NC}"
echo "=================================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Start the Phoenix Scanner Service (if not running):"
echo -e "   ${CYAN}cd ../phoenix-scanner-service${NC}"
echo -e "   ${CYAN}docker-compose up -d${NC}"
echo ""
echo "2. Test the client:"
echo -e "   ${CYAN}python3 test_client.py${NC}"
echo ""
echo "3. Upload your first scan:"
echo -e "   ${CYAN}python3 actions/upload_single.py --file your-scan.json${NC}"
echo ""
echo "4. Read the documentation:"
echo -e "   ${CYAN}README.md${NC} - Full documentation"
echo -e "   ${CYAN}QUICKSTART.md${NC} - Quick start guide"
echo -e "   ${CYAN}USAGE_GUIDE.md${NC} - Detailed usage examples"
echo ""
echo "For help: python3 actions/upload_single.py --help"
echo ""



